<a href="https://colab.research.google.com/github/HeatlerX/229352-LAB07/blob/main/670510758_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [530]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [531]:
a = torch.tensor(2)
a

tensor(2)

In [532]:
b = torch.tensor(3)
a*b

tensor(6)

### Convert a tensor to scalar

In [533]:
c = b.item()
c

3

### Creating 2D tensor

In [534]:
A = torch.tensor([[1,2],[5,6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [535]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [536]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [537]:
torch.cuda.is_available()

True

In [538]:
C.device

device(type='cpu')

In [539]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [540]:
D.device

device(type='cuda', index=0)

In [541]:
#C + D

In [542]:
#D.numpy()

## Basic operations

In [543]:
E= D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

In [544]:
D*2

tensor([[ 2,  4],
        [10, 12]], device='cuda:0')

In [545]:
D-2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [546]:
D.cpu()*np.array([1,2])

/tmp/ipython-input-510672798.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu()*np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [547]:
A = torch.tensor([[4,5],[8,9]])
B = torch.tensor([[1,4],[7,8]])
torch.matmul(A,B)

tensor([[ 39,  56],
        [ 71, 104]])

In [548]:
torch.mm(A,B)

tensor([[ 39,  56],
        [ 71, 104]])

In [549]:
A@B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [550]:
A

tensor([[4, 5],
        [8, 9]])

In [551]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [552]:
a=torch.zeros(1,2,3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [553]:
b =torch.ones(1,2,3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [554]:
T = torch.eye(3)
T

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [555]:
R1=torch.rand(2,3)
R1

tensor([[0.7791, 0.4877, 0.0177],
        [0.4634, 0.8935, 0.4048]])

In [556]:
R2=torch.randn(2,3)
R2

tensor([[-0.7922, -1.0946,  0.8401],
        [ 0.0908, -0.0448, -0.2093]])

In [557]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [558]:
A.shape

torch.Size([2, 2])

In [559]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [560]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [561]:
v=u.reshape(2,3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [562]:
w = u.view(3,2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [563]:
a =torch.arange(4)
b =torch.arange(4)+1
c = torch.stack([a,b],axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [564]:
d=torch.stack([a,b],axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [565]:
# concatenate
e=torch.cat([a,b],axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [566]:
# f=torch.cat([a,b],axis=1)
# f

### Squeezing a tensor (removing an extra dimension)

In [567]:
A = torch.zeros(1,2,3)
B=A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [568]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [569]:
# H.shape = (6, )
C= B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [570]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [571]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [572]:
P[0:3,0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [573]:
torch.inverse(torch.tensor([[2.0,0.0],[0.0,5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [574]:
# X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
# print(X)

# X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
# print(X)

In [575]:
X=torch.rand(200,7)
X.shape


torch.Size([200, 7])

In [576]:
b=torch.rand(8,1)
b.shape

torch.Size([8, 1])

In [577]:
e=torch.rand(200,1)
e.shape

torch.Size([200, 1])

In [578]:
one=torch.ones(200,1)


In [579]:
new_X=torch.cat((one,X),axis=1)
new_X

tensor([[1.0000, 0.9849, 0.6148,  ..., 0.0054, 0.2520, 0.6215],
        [1.0000, 0.4217, 0.6598,  ..., 0.6582, 0.5817, 0.8462],
        [1.0000, 0.1722, 0.6744,  ..., 0.7698, 0.0437, 0.7376],
        ...,
        [1.0000, 0.0587, 0.4674,  ..., 0.1062, 0.0333, 0.4327],
        [1.0000, 0.4315, 0.8824,  ..., 0.5122, 0.3106, 0.9541],
        [1.0000, 0.7261, 0.8907,  ..., 0.6017, 0.7779, 0.7564]])

In [580]:
new_X.shape

torch.Size([200, 8])

In [581]:
y=torch.matmul(new_X,b)+e


In [582]:
b_hat = (torch.inverse(torch.matmul(new_X.t(), new_X)) @ new_X.t()) @ y

In [583]:
b_hat

tensor([[1.4453],
        [0.4385],
        [0.0981],
        [1.0690],
        [0.6499],
        [0.4048],
        [0.2977],
        [0.3476]])

In [584]:
b_hat.shape

torch.Size([8, 1])

In [585]:
y_hat=new_X@b_hat

In [586]:
y_hat.shape

torch.Size([200, 1])

In [587]:
mse=((y-y_hat)**2).sum()/200

In [588]:
mse

tensor(0.0797)